#ifndef _UDP_MESSAGE_STRUCTURE_
#define _UDP_MESSAGE_STRUCTURE_


#define MULTICAST_ADDR "224.0.0.10"
#define MULTICAST_PORT 12345
//#define UDP_MESSAGE_SIZE 65507
#define NUMBER_OF_ARRAY_ELEMENTS_PER_LINE 10

#define UDP_MESSAGE_SIZE 1024
#define NUMBER_OF_ARRAY_ELEMENTS_PER_LINE 10
#define PORT 12345
#endif
